# Generated by Django 5.2.5 on 2025-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_ranksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranksheet',
            name='average',
            field=models.FloatField(),
        ),
    ]
